In [ ]:
#1 Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [27]:
import numpy as np
from numpy import array
x = [12.23, 13.32, 100, 36.32]
y = np.array(x)
print(y)
print(type(x))
print(type(y))

[ 12.23  13.32 100.    36.32]
<class 'list'>
<class 'numpy.ndarray'>


In [32]:
#2 Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

import numpy as np
from numpy import array
x = np.arange(2,11)
y = np.arange(2,11).reshape([3,3])
print(x)
print(y)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [39]:
#3 Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

x = np.zeros(10)
x[6]=11
print(x)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [42]:
#4 Write a NumPy program to create an array with values ranging from 12 to 38.

x = np.arange(12,39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [46]:
#5 Write a NumPy program to reverse an array (first element becomes last)

x = np.arange(12,38)
x[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [55]:
#6 Write a NumPy program to convert an array to a float type

x = [1, 2, 3, 4]
intarray = np.array(x)
floatarray = np.asfarray(intarray)
floatarray

array([1., 2., 3., 4.])

In [62]:
#7 Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
# 8 Write a NumPy program to add a border (filled with 0's) around an existing array.

import numpy as np
myarray = np.ones((3,3))
print(myarray)

pad_arr = np.pad(myarray, pad_width=1, mode = 'constant', 
                 constant_values=0)
  
print(pad_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [72]:
#9 
myarray = np.zeros((8,8))
myarray[1::2,1::2]=1
myarray[::2,::2]=1
print(myarray)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [98]:
#10 Write a NumPy program to convert a list and tuple into arrays

import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print(my_list)
my_array = np.array(my_list)
print(my_array)
print(type(my_list))
print(type(my_array))

[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]
<class 'list'>
<class 'numpy.ndarray'>


In [105]:
my_tuple = ([8, 4, 6], [1, 2, 3])
print(np.asarray(my_tuple))

[[8 4 6]
 [1 2 3]]


In [107]:
#11 Write a NumPy program to append values to the end of an array.

x = [10, 20, 30]
np.append(x,[[40, 50,60],[70, 80, 90]])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [109]:
#12 Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees

x = np.array([0, 12, 45.21 ,34, 99.91])
y = (x * 1.8) + 32
print(y)

[ 32.     53.6   113.378  93.2   211.838]


In [ ]:
#13 

In [114]:
x = [1, 2, 3]
y = np.array(x)
print(y.size)
print(y.itemsize)
print(y.nbytes)

3
8
24


In [123]:
#14 Write a NumPy program to find common values between two arrays.

import numpy as np
Ar1 = np.array([0,10, 20, 40, 60])
Ar2 = [10, 30, 40]       #??????
print(np.intersect1d(Ar1, Ar2))

[10 40]


In [126]:
#15 Write a NumPy program to get the unique elements of an array.

a = np.array([10, 10, 20, 20, 30, 40])
np.unique(a)

array([10, 20, 30, 40])

In [127]:
#16 Write a NumPy program to find the set difference of two arrays. 

ar1 = np.array([0, 10, 20, 40, 60, 80])
ar2 = np.array([10, 30, 40, 50, 70])
# set difference ar1 - ar2
ar1_2_diff = np.setdiff1d(ar1, ar2)
# display the array
print(ar1_2_diff)

[ 0 20 60 80]


In [128]:
#17 Write a NumPy program to find the set exclusive-or of two arrays.

import numpy as np
arr1 = np.array([[0, 10, 20, 40, 60, 80]])
arr2 = [10, 30, 40, 50, 70]
print(np.setxor1d(arr1, arr2))

[ 0 20 30 50 60 70 80]


In [129]:
#18 Write a NumPy program to find the union of two arrays.

import numpy as np
arr1 = np.array([[0, 10, 20, 40, 60, 80]])
arr2 = [10, 30, 40, 50, 70]
print(np.union1d(arr1, arr2))

[ 0 10 20 30 40 50 60 70 80]


In [130]:
#19 Write a NumPy program to test whether all elements in an array evaluate to True.

import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


In [132]:
#20 Write a NumPy program to find the indices of the maximum and minimum values 

import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array:",x)
print("Maximum Values:",np.argmax(x))
print("Minimum Values:",np.argmin(x))

Original array: [1 2 3 4 5 6]
Maximum Values: 5
Minimum Values: 0


In [138]:
#21

import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Given array ",x)
print("Values bigger than 10 are ",x[x>10])
print("Their indicies are ",np.nonzero(x>10))

Given array  [[ 0 10 20]
 [20 30 40]]
Values bigger than 10 are  [20 20 30 40]
Their indicies are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


In [140]:
#22 Write a NumPy program to create an array of ones of size 2, and an array of zeros of size 2

import numpy as np
x = np.ones(2)
y = np.zeros(2)
print(x)
print(y)

[1. 1.]
[0. 0.]


In [142]:
#23 Write a NumPy program to create a contiguous flattened array


x = np.array ([[10, 20, 30],[20, 40, 50]])
print("Original array:",x)
print("Flattened array:", np.ravel(x))


Original array: [[10 20 30]
 [20 40 50]]
Flattened array: [10 20 30 20 40 50]


In [143]:
#24 Write a NumPy program to create a new shape to an array without changing its data.

import numpy as np
from numpy import array
x = np.array([1, 2, 3, 4, 5, 6])
np.reshape(x,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
np.reshape(x,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
#25 Write a NumPy program to change the data type of an array.

x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print(x.dtype)
y = np.float64(x)
print(y)
print(y.dtype)

[[ 2  4  6]
 [ 6  8 10]]
int32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
float64


In [150]:
#26 Write a NumPy program to create a 1-D array of 20 element ...

import numpy as np
x =  np.logspace(2., 5., 20, endpoint=False)
print(x)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


In [151]:
#27 Write a NumPy program to concatenate two 2-dimensional arrays. 

import numpy as np
x = np.array([[0, 1, 3], [5, 7, 9]])
y = np.array([[0, 2, 4], [6, 8, 10]])
z1 = np.concatenate((x,y),1)
print(z1)
print(z1.shape)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
(2, 6)


In [152]:
#28 

import numpy as np
x = np.arange(1, 15)
print("Original array:",x)
print("After splitting:")
print(np.split(x, [2, 6]))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [154]:
#29 

import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting:")
print(np.hsplit(x, [2, 6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]


In [155]:
#30

x = np.array([[0, 10, 20],[20, 30, 40]])
np.count_nonzero(x)

5

In [168]:
#31 Write a NumPy program to add an extra column to a NumPy array.

import numpy as np
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [169]:
#32 Write a NumPy program to remove the negative values in a NumPy array with 0.

import numpy as np
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
x[x < 0] = 0
print(x)

[0 0 0 2 3 4 5 0]


In [170]:
#33 

import numpy as np
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [1, 0, 1]])
print("Original array:")
print(x)
print("Remove all non-numeric elements of the array")
print(x[~np.isnan(x).any(axis=1)])

Original array:
[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
Remove all non-numeric elements of the array
[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


In [174]:
#34 Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.

import numpy as np
a = np.array([97, 101, 105, 111, 117]) 
b = np.array(['a','e','i','o','u'])
print("Original arrays")
print(a)
print(b)
print("Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:")
print(b[(100 < a) & (a < 110)])

Original arrays
[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
Elements from the second array  corresponding to elements in the first array n\  that are greater than 100 and less than 110:
['e' 'i']


In [178]:
#35 Write a NumPy program to count the frequency of unique values in numpy array.

import numpy as np
a = np.array( [10,10,20,10,20,20,20,30,30,50,40,40])
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [181]:
#36 Write a NumPy program to access last two columns of a multidimensional columns.

import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arra)
result = x[:,[1,2]]
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
